{
  "hash": "dbf7b4d9d35fc298e14c2adea92b4d59",
  "result": {
    "engine": "knitr",
    "markdown": "# Differential equations\n\n\n\n## Overview\n\nThis chapter develops six connected differential-equation ideas:\n\n1. forming differential equations from statements about rates of change;\n2. solving separable differential equations;\n3. using initial conditions to find particular solutions;\n4. modelling growth, decay and saturation;\n5. modelling cooling and weather-type relaxation;\n6. interpreting deterministic models in contexts such as finance and environmental data.\n\nThe central technique in this chapter is **separating the variables**. We will not use integrating factors, second-order differential equations, or stochastic differential equations as solution techniques.\n\n::: {.callout-note}\nThe exercises are organised into tiers.\n\n**Bronze** develops fluency.  \n**Silver** develops simple application.  \n**Gold** develops exam-style reasoning.  \nThe **STEP-style** section extends the chapter beyond routine A Level fluency.\n:::\n\n::: {.callout-warning}\nReal-world data changes. The R examples in this chapter use small classroom datasets so that the book renders offline. Before using the notes for a live lesson, update the contextual values from official sources such as NIWA, Vietnam's national hydrometeorological service, the Reserve Bank of New Zealand, or a bank exchange-rate feed.\n:::\n\n## Inspiration: differential equations behind real-world data\n\nDifferential equations are not just symbolic exercises. They are one of the main languages used to describe change in the real world.\n\nIn this chapter, our technique is deliberately limited to **separating the variables**. However, the same basic idea sits underneath much more sophisticated models used in weather forecasting, finance, population modelling, epidemics, cooling, chemical reactions and environmental science.\n\nThe guiding question is:\n\n> If we know how fast something changes, can we predict what happens next?\n\nReal applications usually begin with data. For example:\n\n- weather observations from New Zealand and Vietnam;\n- temperature, rainfall, wind and sunshine summaries;\n- exchange-rate data such as NZD/VND or USD/VND;\n- population or environmental indices;\n- school-based data such as attendance, enrolment, revision completion or assessment readiness.\n\nThe full real-world models may be complicated. But in this chapter we study simplified models that still capture the same central idea: **a rate of change determines a future state**.\n\n### From real-world systems to differential equations\n\n| Context | Real-world data students can recognise | More advanced differential-equation model | Separable model used in this chapter |\n|---|---|---|---|\n| Weather forecasting | Temperature, rainfall, wind speed, pressure | Coupled nonlinear partial differential equations from fluid dynamics and thermodynamics | $\\dfrac{dT}{dt}=-k(T-A)$ |\n| Cooling and heating | Tea cooling in a room, classroom temperature, outdoor/indoor comparison | Heat equation or energy-balance models | $\\dfrac{dT}{dt}=-k(T-A)$ |\n| Population growth | Population index, school roll, bacteria growth | Logistic or multi-compartment systems | $\\dfrac{dP}{dt}=kP\\left(1-\\dfrac{P}{M}\\right)$ |\n| Finance | Exchange rates, investment indices, price series | Stochastic differential equations with random noise | $\\dfrac{dS}{dt}=rS$ |\n| Epidemics | Number infected, recovered or susceptible | Coupled SIR-type differential equations | $\\dfrac{dI}{dt}=kI$ or $\\dfrac{dI}{dt}=kI(M-I)$ |\n| Environmental recovery | Pollution level, rainfall deficit, concentration decay | Transport-diffusion-reaction equations | $\\dfrac{dC}{dt}=-kC$ |\n\nThe important point is that our simple models are not the whole story. They are **entry points** into the same mathematical way of thinking.\n\n### Example 1: weather and climate\n\nModern weather forecasting does not use one simple equation. A full numerical weather model may involve velocity, pressure, temperature, moisture, radiation, surface effects and the rotation of the Earth.\n\nA simplified momentum equation may contain terms such as\n\n$$\n\\dfrac{D\\mathbf{u}}{Dt}\n+\nf\\mathbf{k}\\times\\mathbf{u}\n=\n-\\dfrac{1}{\\rho}\\nabla p\n+\n\\mathbf{g}\n+\n\\nu\\nabla^2\\mathbf{u}.\n$$\n\nThis is far beyond our course. It is a partial differential equation involving vectors, pressure gradients, rotation and diffusion.\n\nBut a simple classroom version might ask:\n\n> A hot surface cools towards the surrounding air temperature. How does its temperature change?\n\nThat leads to the separable model\n\n$$\n\\dfrac{dT}{dt}=-k(T-A),\n$$\n\nwhere $A$ is the ambient temperature.\n\nThis simple equation already captures an important real-world behaviour: the further $T$ is from $A$, the faster it changes.\n\n### Example 2: finance and exchange rates\n\nFinancial data such as NZD/VND or USD/VND exchange rates do not move smoothly. They respond to interest rates, trade, policy, news, expectations and market shocks.\n\nA more advanced stochastic model may be written as\n\n$$\ndS_t=\\mu S_t\\,dt+\\sigma S_t\\,dW_t.\n$$\n\nHere, the term\n\n$$\n\\mu S_t\\,dt\n$$\n\nrepresents the deterministic trend, while\n\n$$\n\\sigma S_t\\,dW_t\n$$\n\nrepresents random fluctuation.\n\nStochastic differential equations are not part of this chapter. However, if we ignore the random term temporarily, we get the separable deterministic model\n\n$$\n\\dfrac{dS}{dt}=\\mu S.\n$$\n\nSolving this gives\n\n$$\nS=S_0e^{\\mu t}.\n$$\n\nSo the model in this chapter is a simplified backbone for a much more complex financial idea.\n\n### Example 3: epidemics and saturation\n\nA simple early-stage epidemic model may assume that the number of infected individuals grows at a rate proportional to the current number infected:\n\n$$\n\\dfrac{dI}{dt}=kI.\n$$\n\nThis gives exponential growth:\n\n$$\nI=I_0e^{kt}.\n$$\n\nBut unlimited exponential growth is not realistic. In a fixed population, growth slows down as the number of susceptible people decreases.\n\nA more realistic model may involve several coupled equations, such as a susceptible-infected-recovered system. A simplified version in this chapter is logistic growth:\n\n$$\n\\dfrac{dP}{dt}=kP\\left(1-\\dfrac{P}{M}\\right).\n$$\n\nThis is still separable, but it captures a better idea: growth is fast at first, then slows as the quantity approaches a maximum capacity $M$.\n\n### Visualisation using R\n\nThe graph below compares three simplified model shapes. The values are scaled so that the shapes can be compared on one plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntime_values <- seq(0, 12, length.out = 600)\n\ninspiration_df <- data.frame(\n  time = rep(time_values, 3),\n  context = rep(\n    c(\n      \"cooling towards ambient\",\n      \"deterministic financial growth\",\n      \"logistic saturation\"\n    ),\n    each = length(time_values)\n  )\n)\n\ncooling_values <- 26 + (80 - 26) * exp(-0.25 * time_values)\nfinance_values <- 15000 * exp(0.04 * time_values)\nlogistic_values <- 1000 / (1 + 9 * exp(-0.7 * time_values))\n\ninspiration_df$model_value <- c(\n  cooling_values,\n  finance_values,\n  logistic_values\n)\n\ninspiration_df$scaled_value <- ave(\n  inspiration_df$model_value,\n  inspiration_df$context,\n  FUN = function(values) {\n    (values - min(values)) / (max(values) - min(values))\n  }\n)\n\nggplot(inspiration_df, aes(x = time, y = scaled_value, linetype = context)) +\n  geom_line(linewidth = 1.1) +\n  labs(\n    title = \"Differential equations model different types of change\",\n    subtitle = \"The values are scaled so the shapes can be compared.\",\n    x = \"time\",\n    y = \"scaled model value\",\n    linetype = \"Context\"\n  ) +\n  book_theme()\n```\n\n::: {.cell-output-display}\n![Three simplified differential-equation model shapes.](10-differential-equations_files/figure-pdf/fig-real-world-de-inspiration-1.pdf){#fig-real-world-de-inspiration fig-pos='H'}\n:::\n:::\n\n### Real-world example: using a differential equation to model an NZ bank-related share price\n\nHeartland Group Holdings Limited is listed on the NZX under the ticker HGH. Heartland describes its story as one involving specialist finance and banking products, so this gives us a useful New Zealand financial context for a differential-equations model.\n\nThe NZX page for HGH gives the following delayed market data:\n\n\n::: {#tbl-hgh-real-nzx-data .cell}\n\n```{.r .cell-code}\nhgh_data <- data.frame(\n  source = \"NZX delayed market data\",\n  ticker = \"HGH\",\n  company = \"Heartland Group Holdings Limited\",\n  data_timestamp = \"27/06/2026, 16:31 NZST\",\n  current_price_nzd = 1.2050,\n  change_52_week_nzd = 0.4350,\n  change_52_week_percent = 56.49\n)\n\nhgh_data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   source ticker                          company\n1 NZX delayed market data    HGH Heartland Group Holdings Limited\n          data_timestamp current_price_nzd change_52_week_nzd\n1 27/06/2026, 16:31 NZST             1.205              0.435\n  change_52_week_percent\n1                  56.49\n```\n\n\n:::\n:::\n\n\nThis gives us two real data points for a simple classroom model.\n\nThe current price is approximately\n\n$$\nS(1)=1.205.\n$$\n\nThe 52-week change is approximately\n\n$$\n0.435.\n$$\n\nSo the approximate price one year earlier was\n\n$$\nS(0)=1.205-0.435=0.770.\n$$\n\nWe now model the share price $S$ using the separable differential equation\n\n$$\n\\dfrac{dS}{dt}=rS,\n$$\n\nwhere $t$ is measured in years from approximately 52 weeks ago.\n\nSeparating the variables gives\n\n$$\n\\dfrac{1}{S}\\dfrac{dS}{dt}=r.\n$$\n\nSo\n\n$$\n\\int \\dfrac{1}{S}\\,dS=\\int r\\,dt.\n$$\n\nHence\n\n$$\n\\ln S=rt+C.\n$$\n\nTherefore,\n\n$$\nS=S_0e^{rt}.\n$$\n\nUsing the real NZX data,\n\n$$\nS(0)=0.770\n$$\n\nand\n\n$$\nS(1)=1.205.\n$$\n\nSo\n\n$$\n1.205=0.770e^r.\n$$\n\nTherefore,\n\n$$\ne^r=\\dfrac{1.205}{0.770}.\n$$\n\nTaking logarithms gives\n\n$$\nr=\\ln\\left(\\dfrac{1.205}{0.770}\\right).\n$$\n\nThus\n\n$$\nr\\approx0.448.\n$$\n\nThe fitted differential-equation model is\n\n$$\nS(t)=0.770e^{0.448t}.\n$$\n\n::: {.callout-warning}\nThis is not investment advice and not a genuine financial forecast. It is a mathematical modelling example using two real NZX data points. Real share prices are affected by earnings, interest rates, dividends, credit conditions, market sentiment, news and random shocks.\n:::\n\n### Visualisation using R: fitting the model to real NZX data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprice_current <- 1.2050\nchange_52_week <- 0.4350\nprice_one_year_ago <- price_current - change_52_week\n\ngrowth_rate <- log(price_current / price_one_year_ago)\n\nobserved_prices <- data.frame(\n  t = c(0, 1),\n  price = c(price_one_year_ago, price_current),\n  label = c(\"approx. 52 weeks ago\", \"current NZX price\")\n)\n\nfitted_curve <- data.frame(\n  t = seq(0, 1, length.out = 400)\n)\n\nfitted_curve$price <- price_one_year_ago * exp(growth_rate * fitted_curve$t)\n\nggplot() +\n  geom_line(data = fitted_curve, aes(x = t, y = price), linewidth = 1.1) +\n  geom_point(data = observed_prices, aes(x = t, y = price), size = 3) +\n  geom_text(\n    data = observed_prices,\n    aes(x = t, y = price, label = label),\n    nudge_y = 0.05\n  ) +\n  labs(\n    title = \"Fitting dS/dt = rS to real NZX HGH data\",\n    subtitle = paste0(\"Estimated continuous annual rate r = \", round(growth_rate, 3)),\n    x = \"time in years from approximately 52 weeks ago\",\n    y = \"share price in NZD\"\n  ) +\n  book_theme()\n```\n\n::: {.cell-output-display}\n![A separable differential-equation model fitted to real NZX HGH data.](10-differential-equations_files/figure-pdf/fig-hgh-real-nzx-fit-1.pdf){#fig-hgh-real-nzx-fit fig-pos='H'}\n:::\n:::\n\n\n### A light prediction\n\nA full one-year extrapolation would be too aggressive for a classroom model based on only two data points. Instead, we make a light 13-week projection.\n\nSince\n\n$$\n13\\text{ weeks}=\\dfrac{13}{52}\\text{ years}=0.25\\text{ years},\n$$\n\nwe estimate\n\n$$\nS(1.25)=1.205e^{0.448(0.25)}.\n$$\n\nThis gives\n\n$$\nS(1.25)\\approx1.348.\n$$\n\nSo the simple model gives a light 13-week projection of approximately\n\n$$\n\\$1.35.\n$$\n\nThis should be interpreted as a mathematical projection, not a financial prediction.\n\n\n::: {#tbl-hgh-light-prediction .cell}\n\n```{.r .cell-code}\nprediction_weeks <- c(4, 8, 13)\nprediction_years <- prediction_weeks / 52\n\nprediction_table <- data.frame(\n  weeks_after_current_price = prediction_weeks,\n  years_after_current_price = round(prediction_years, 3),\n  predicted_price_nzd = round(price_current * exp(growth_rate * prediction_years), 3)\n)\n\nprediction_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  weeks_after_current_price years_after_current_price predicted_price_nzd\n1                         4                     0.077               1.247\n2                         8                     0.154               1.291\n3                        13                     0.250               1.348\n```\n\n\n:::\n:::\n\n\n### Visualisation using R: light prediction region\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprediction_curve <- data.frame(\n  t = seq(0, 1.25, length.out = 600)\n)\n\nprediction_curve$price <- price_one_year_ago * exp(growth_rate * prediction_curve$t)\nprediction_curve$interval <- ifelse(\n  prediction_curve$t <= 1,\n  \"observed 52-week interval\",\n  \"13-week projection\"\n)\n\nfuture_point <- data.frame(\n  t = 1.25,\n  price = price_current * exp(growth_rate * 0.25),\n  label = \"13-week projection\"\n)\n\nggplot() +\n  annotate(\n    \"rect\",\n    xmin = 1,\n    xmax = 1.25,\n    ymin = -Inf,\n    ymax = Inf,\n    alpha = 0.12\n  ) +\n  geom_line(\n    data = prediction_curve,\n    aes(x = t, y = price, linetype = interval),\n    linewidth = 1.1\n  ) +\n  geom_point(data = observed_prices, aes(x = t, y = price), size = 3) +\n  geom_point(data = future_point, aes(x = t, y = price), size = 3) +\n  geom_text(\n    data = future_point,\n    aes(x = t, y = price, label = label),\n    nudge_y = 0.05\n  ) +\n  labs(\n    title = \"Light projection from dS/dt = rS\",\n    subtitle = \"The shaded region shows the 13-week extrapolation beyond the real NZX data.\",\n    x = \"time in years from approximately 52 weeks ago\",\n    y = \"share price in NZD\",\n    linetype = \"Interval\"\n  ) +\n  book_theme()\n```\n\n::: {.cell-output-display}\n![A light 13-week projection from the fitted differential-equation model.](10-differential-equations_files/figure-pdf/fig-hgh-light-prediction-1.pdf){#fig-hgh-light-prediction fig-pos='H'}\n:::\n:::\n\n\n### Scenario check\n\nBecause the fitted value\n\n$$\nr\\approx0.448\n$$\n\ncomes from a strong 52-week movement, it is risky to assume that this rate continues. A more honest modelling approach is to compare scenarios.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfuture_time <- seq(0, 0.25, length.out = 300)\n\nscenario_df <- expand.grid(\n  years_after_current_price = future_time,\n  scenario = c(\n    \"same fitted rate\",\n    \"half fitted rate\",\n    \"zero growth\",\n    \"negative half fitted rate\"\n  )\n)\n\nscenario_df$rate <- ifelse(\n  scenario_df$scenario == \"same fitted rate\",\n  growth_rate,\n  ifelse(\n    scenario_df$scenario == \"half fitted rate\",\n    growth_rate / 2,\n    ifelse(\n      scenario_df$scenario == \"zero growth\",\n      0,\n      -growth_rate / 2\n    )\n  )\n)\n\nscenario_df$predicted_price <- price_current * exp(\n  scenario_df$rate * scenario_df$years_after_current_price\n)\n\nggplot(scenario_df, aes(x = years_after_current_price, y = predicted_price, linetype = scenario)) +\n  geom_line(linewidth = 1.1) +\n  geom_hline(yintercept = price_current, linetype = \"dashed\") +\n  labs(\n    title = \"Scenario check for a 13-week projection\",\n    subtitle = \"The model is sensitive to the assumed continuous rate r.\",\n    x = \"years after current NZX price\",\n    y = \"projected share price in NZD\",\n    linetype = \"Scenario\"\n  ) +\n  book_theme()\n```\n\n::: {.cell-output-display}\n![Scenario comparison after the current NZX price.](10-differential-equations_files/figure-pdf/fig-hgh-real-nzx-scenario-check-1.pdf){#fig-hgh-real-nzx-scenario-check fig-pos='H'}\n:::\n:::\n\n\n### Interpretation\n\nThis example follows the modelling cycle:\n\n$$\n\\text{real NZX data}\n\\quad\\longrightarrow\\quad\n\\dfrac{dS}{dt}=rS\n\\quad\\longrightarrow\\quad\nS=S_0e^{rt}\n\\quad\\longrightarrow\\quad\n\\text{fit }r\n\\quad\\longrightarrow\\quad\n\\text{make a cautious projection}.\n$$\n\nThe strength of the differential equation is that the assumption is explicit:\n\n> The price changes at a rate proportional to the current price.\n\nOnce that assumption is made, the mathematics forces an exponential model. The final step is not just calculation, but critique: we ask whether the assumption is reasonable.\n\n### Why we still study simple separable models\n\nA simple separable differential equation is useful because it teaches the core modelling cycle:\n\n1. identify the changing quantity;\n2. describe its rate of change;\n3. write a differential equation;\n4. separate the variables;\n5. integrate;\n6. use an initial condition;\n7. interpret the solution in context.\n\nThe models in this chapter are simplified, but they are not artificial. They are the first layer of the same mathematical thinking used in larger models.\n\nFor example,\n\n$$\n\\dfrac{dT}{dt}=-k(T-A)\n$$\n\nis not a full weather model, but it captures relaxation towards an ambient value.\n\nSimilarly,\n\n$$\n\\dfrac{dS}{dt}=rS\n$$\n\nis not a full financial model, but it captures the deterministic backbone of continuous growth or decay.\n\nAnd\n\n$$\n\\dfrac{dP}{dt}=kP\\left(1-\\dfrac{P}{M}\\right)\n$$\n\nis not a full population or epidemic model, but it captures the idea that growth slows as a limiting capacity is approached.\n\nThis chapter therefore acts as a bridge:\n\n$$\n\\text{data}\n\\quad\\longrightarrow\\quad\n\\text{rate of change}\n\\quad\\longrightarrow\\quad\n\\text{differential equation}\n\\quad\\longrightarrow\\quad\n\\text{solution}\n\\quad\\longrightarrow\\quad\n\\text{interpretation}.\n$$\n\n## 10.1 Forming differential equations from rates of change\n\n### Key mathematical ideas\n\nA differential equation describes how a quantity changes.\n\nIf a quantity $y$ changes with respect to $x$, then its rate of change is\n\n$$\n\\dfrac{dy}{dx}.\n$$\n\nMany modelling statements translate directly into differential equations.\n\nIf $y$ increases at a rate proportional to $y$, then\n\n$$\n\\dfrac{dy}{dx}=ky,\n$$\n\nwhere $k>0$.\n\nIf $y$ decreases at a rate proportional to $y$, then\n\n$$\n\\dfrac{dy}{dx}=-ky,\n$$\n\nwhere $k>0$.\n\nIf a temperature $T$ approaches an ambient temperature $A$, then a common model is\n\n$$\n\\dfrac{dT}{dt}=-k(T-A),\n$$\n\nwhere $k>0$.\n\nThis means the rate of temperature change depends on the difference between the current temperature and the ambient temperature.\n\n### Visualisation using R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfield_df <- slope_field(\n  x_min = 0,\n  x_max = 4,\n  y_min = 0,\n  y_max = 6,\n  derivative_function = function(x_value, y_value) 0.5 * y_value\n)\n\ncurve_df <- data.frame(\n  x = seq(0, 4, length.out = 400)\n)\n\ncurve_df$y <- 2 * exp(0.5 * curve_df$x)\n\nggplot() +\n  geom_segment(\n    data = field_df,\n    aes(x = xstart, y = ystart, xend = xend, yend = yend),\n    alpha = 0.55\n  ) +\n  geom_line(data = curve_df, aes(x = x, y = y), linewidth = 1.1) +\n  labs(\n    title = \"A rate proportional to the current amount\",\n    subtitle = \"When dy/dx = 0.5y, larger y-values have steeper gradients.\",\n    x = \"x\",\n    y = \"y\"\n  ) +\n  book_theme()\n```\n\n::: {.cell-output-display}\n![Slope field for dy/dx = 0.5y.](10-differential-equations_files/figure-pdf/fig-growth-slope-field-1.pdf){#fig-growth-slope-field fig-pos='H'}\n:::\n:::\n\n\n### Worked example\n\nA cup of tea has temperature $T$ degrees Celsius after $t$ minutes. The surrounding air temperature is $22^\\circ\\text{C}$. The tea cools at a rate proportional to how much hotter it is than the surrounding air.\n\nForm a differential equation.\n\nThe temperature difference is\n\n$$\nT-22.\n$$\n\nSince the tea is cooling, the rate of change is negative when $T>22$.\n\nTherefore,\n\n$$\n\\dfrac{dT}{dt}=-k(T-22),\n\\quad k>0.\n$$\n\nThis equation also has the sensible equilibrium\n\n$$\nT=22,\n$$\n\nbecause when $T=22$,\n\n$$\n\\dfrac{dT}{dt}=0.\n$$\n\n### Short investigation\n\nThe following table translates modelling language into differential equations.\n\n\n::: {#tbl-rate-language .cell}\n\n```{.r .cell-code}\ndata.frame(\n  statement = c(\n    \"growth proportional to amount\",\n    \"decay proportional to amount\",\n    \"cooling towards ambient A\",\n    \"saturation towards capacity M\",\n    \"logistic growth with capacity M\"\n  ),\n  differential_equation = c(\n    \"dy/dt = ky\",\n    \"dy/dt = -ky\",\n    \"dT/dt = -k(T - A)\",\n    \"dW/dt = k(M - W)\",\n    \"dP/dt = kP(1 - P/M)\"\n  )\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                        statement differential_equation\n1   growth proportional to amount            dy/dt = ky\n2    decay proportional to amount           dy/dt = -ky\n3       cooling towards ambient A     dT/dt = -k(T - A)\n4   saturation towards capacity M      dW/dt = k(M - W)\n5 logistic growth with capacity M   dP/dt = kP(1 - P/M)\n```\n\n\n:::\n:::\n\n\n### Exercises 10.1\n\n#### Bronze\n\n1. A quantity $y$ increases at a rate proportional to $y$. Write a differential equation.\n2. A quantity $y$ decreases at a rate proportional to $y$. Write a differential equation.\n3. A population $P$ decreases at $5\\%$ per hour. Write a differential equation.\n4. A speed $v$ decreases at a rate proportional to $v^2$. Write a differential equation.\n5. A water level $W$ rises towards a maximum level $M$ at a rate proportional to $M-W$. Write a differential equation.\n\n#### Silver\n\n1. A drink of temperature $T$ cools in a room of temperature $22^\\circ\\text{C}$. Its rate of cooling is proportional to $T-22$. Write a differential equation.\n2. A number of infected individuals $I$ grows at a rate proportional to $I(1000-I)$. Write a differential equation.\n3. A deterministic exchange-rate model assumes a value $S$ changes at a rate proportional to $S$. Write a differential equation.\n4. A rainfall deficit $D$ decreases at a rate proportional to $D$. Write a differential equation.\n5. A population satisfies $\\dfrac{dN}{dt}=kN$ and has initial value $200$. Write the initial condition.\n\n#### Gold\n\n1. A cold object warms towards ambient temperature $30^\\circ\\text{C}$ at a rate proportional to the temperature difference. Write a differential equation.\n2. The rate of increase of $y$ with respect to $x$ is proportional to $xy$. Write a differential equation.\n3. The rate of decrease of $y$ with respect to $x$ is proportional to $\\dfrac{y}{1+x}$. Write a differential equation.\n4. A population $P$ grows logistically with carrying capacity $5000$. Write a suitable differential equation.\n5. Explain why $T=A$ is an equilibrium solution of $\\dfrac{dT}{dt}=-k(T-A)$.\n\n## 10.2 Solving separable differential equations\n\n### Key mathematical ideas\n\nA first-order differential equation is **separable** if it can be rearranged so that all the $y$ terms are on one side and all the $x$ terms are on the other.\n\nFor example,\n\n$$\n\\dfrac{dy}{dx}=xy\n$$\n\ncan be rearranged as\n\n$$\n\\dfrac{1}{y}\\dfrac{dy}{dx}=x.\n$$\n\nThis leads to\n\n$$\n\\int \\dfrac{1}{y}\\,dy=\\int x\\,dx.\n$$\n\nSo\n\n$$\n\\ln|y|=\\dfrac{x^2}{2}+C.\n$$\n\nA common final form is\n\n$$\ny=Ae^{\\dfrac{x^2}{2}},\n$$\n\nwhere $A$ is a non-zero constant.\n\n### Visualisation using R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx_values <- seq(-2, 2, length.out = 600)\n\nsolution_df <- expand.grid(\n  x = x_values,\n  initial_value = c(1, 2, 4)\n)\n\nsolution_df$y <- solution_df$initial_value * exp(solution_df$x^2)\nsolution_df$curve_label <- paste0(\"y(0) = \", solution_df$initial_value)\n\nggplot(solution_df, aes(x = x, y = y, linetype = curve_label)) +\n  geom_line(linewidth = 1.1) +\n  coord_cartesian(ylim = c(0, 25)) +\n  labs(\n    title = \"Solution family for dy/dx = 2xy\",\n    subtitle = \"Different initial conditions give different curves.\",\n    x = \"x\",\n    y = \"y\",\n    linetype = \"Initial condition\"\n  ) +\n  book_theme()\n```\n\n::: {.cell-output-display}\n![A family of solutions to dy/dx = 2xy.](10-differential-equations_files/figure-pdf/fig-solution-family-2xy-1.pdf){#fig-solution-family-2xy fig-pos='H'}\n:::\n:::\n\n\n### Worked example\n\nSolve\n\n$$\n\\dfrac{dy}{dx}=2xy.\n$$\n\nSeparate the variables:\n\n$$\n\\dfrac{1}{y}\\dfrac{dy}{dx}=2x.\n$$\n\nIntegrate both sides:\n\n$$\n\\int \\dfrac{1}{y}\\,dy\n=\n\\int 2x\\,dx.\n$$\n\nSo\n\n$$\n\\ln|y|=x^2+C.\n$$\n\nExponentiating gives\n\n$$\n|y|=e^{x^2+C}=e^C e^{x^2}.\n$$\n\nSo the general solution may be written as\n\n$$\ny=Ae^{x^2},\n$$\n\nwhere $A$ is a constant.\n\n### Short investigation\n\nCheck the solution numerically by differentiating the expression in R.\n\n\n::: {#tbl-solution-check-2xy .cell}\n\n```{.r .cell-code}\nx_values <- c(-1, 0, 1, 2)\ny_values <- 3 * exp(x_values^2)\ndy_dx_values <- 6 * x_values * exp(x_values^2)\nright_side_values <- 2 * x_values * y_values\n\ndata.frame(\n  x = x_values,\n  y = round(y_values, 5),\n  derivative = round(dy_dx_values, 5),\n  right_side = round(right_side_values, 5)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   x         y derivative right_side\n1 -1   8.15485  -16.30969  -16.30969\n2  0   3.00000    0.00000    0.00000\n3  1   8.15485   16.30969   16.30969\n4  2 163.79445  655.17780  655.17780\n```\n\n\n:::\n:::\n\n\n### Exercises 10.2\n\n#### Bronze\n\n1. Solve $\\dfrac{dy}{dx}=3x^2$.\n2. Solve $\\dfrac{dy}{dx}=2xy$.\n3. Solve $\\dfrac{dy}{dx}=y$.\n4. Solve $\\dfrac{dy}{dx}=\\dfrac{x}{y}$.\n5. Solve $\\dfrac{dy}{dx}=4xy^2$.\n\n#### Silver\n\n1. Solve $\\dfrac{dy}{dx}=(x+1)y$, given that $y=2$ when $x=0$.\n2. Solve $\\dfrac{dy}{dx}=\\dfrac{3x}{y}$, given that $y=4$ when $x=0$.\n3. Solve $\\dfrac{dy}{dx}=\\dfrac{y}{1+x}$, given that $y=5$ when $x=0$.\n4. Solve $\\dfrac{dy}{dx}=2x(1+y)$, given that $y=0$ when $x=0$.\n5. Solve $\\dfrac{dy}{dx}=\\dfrac{6x}{y+1}$, given that $y=2$ when $x=0$.\n\n#### Gold\n\n1. Solve $\\dfrac{dy}{dx}=xy^2$, given that $y=1$ when $x=0$.\n2. Solve $\\dfrac{dy}{dx}=y\\cos x$, given that $y=3$ when $x=0$.\n3. Solve $\\dfrac{dy}{dx}=\\dfrac{1+x}{y}$, given that $y=1$ when $x=0$.\n4. Solve $\\dfrac{dy}{dx}=e^xy^2$, given that $y=2$ when $x=0$.\n5. Solve $\\dfrac{dy}{dx}=(2x+1)(y-4)$, given that $y=5$ when $x=0$.\n\n## 10.3 Particular solutions and interpretation\n\n### Key mathematical ideas\n\nA **general solution** contains an arbitrary constant.\n\nA **particular solution** uses extra information, usually an initial condition, to find that constant.\n\nFor example, the general solution\n\n$$\ny=Ae^{x^2}\n$$\n\nbecomes a particular solution if we know the value of $y$ at one point.\n\nIf\n\n$$\ny(0)=7,\n$$\n\nthen\n\n$$\n7=Ae^0=A.\n$$\n\nSo the particular solution is\n\n$$\ny=7e^{x^2}.\n$$\n\n### Visualisation using R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx_values <- seq(-1.5, 1.5, length.out = 600)\n\ncurve_df <- data.frame(\n  x = x_values,\n  y = 7 * exp(x_values^2)\n)\n\npoint_df <- data.frame(\n  x = 0,\n  y = 7,\n  label = \"(0, 7)\"\n)\n\nggplot() +\n  geom_line(data = curve_df, aes(x = x, y = y), linewidth = 1.1) +\n  geom_point(data = point_df, aes(x = x, y = y), size = 3) +\n  geom_text(data = point_df, aes(x = x, y = y, label = label), nudge_y = 3) +\n  labs(\n    title = \"Particular solution\",\n    subtitle = \"The initial condition selects one curve from the family.\",\n    x = \"x\",\n    y = \"y\"\n  ) +\n  book_theme()\n```\n\n::: {.cell-output-display}\n![The solution y = 7e^(x^2) passes through (0, 7).](10-differential-equations_files/figure-pdf/fig-particular-solution-through-point-1.pdf){#fig-particular-solution-through-point fig-pos='H'}\n:::\n:::\n\n\n### Worked example\n\nSolve\n\n$$\n\\dfrac{dy}{dx}=\\dfrac{3y}{1+x},\n\\quad y(0)=2.\n$$\n\nSeparate the variables:\n\n$$\n\\dfrac{1}{y}\\dfrac{dy}{dx}=\\dfrac{3}{1+x}.\n$$\n\nIntegrate:\n\n$$\n\\int \\dfrac{1}{y}\\,dy\n=\n\\int \\dfrac{3}{1+x}\\,dx.\n$$\n\nSo\n\n$$\n\\ln|y|=3\\ln|1+x|+C.\n$$\n\nFor the solution through $x=0$, we work on the interval\n\n$$\nx>-1.\n$$\n\nThus\n\n$$\n\\ln|y|=\\ln(1+x)^3+C.\n$$\n\nHence\n\n$$\ny=A(1+x)^3.\n$$\n\nUsing $y(0)=2$ gives\n\n$$\n2=A.\n$$\n\nTherefore,\n\n$$\ny=2(1+x)^3,\n\\quad x>-1.\n$$\n\n### Short investigation\n\nUse R to compare several particular solutions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx_values <- seq(-0.9, 2, length.out = 600)\n\nsolution_df <- expand.grid(\n  x = x_values,\n  initial_value = c(1, 2, 4)\n)\n\nsolution_df$y <- solution_df$initial_value * (1 + solution_df$x)^3\nsolution_df$curve_label <- paste0(\"y(0) = \", solution_df$initial_value)\n\nggplot(solution_df, aes(x = x, y = y, linetype = curve_label)) +\n  geom_line(linewidth = 1.1) +\n  labs(\n    title = \"Initial conditions change the constant\",\n    subtitle = \"The shape is controlled by the differential equation; the starting value selects the curve.\",\n    x = \"x\",\n    y = \"y\",\n    linetype = \"Initial condition\"\n  ) +\n  book_theme()\n```\n\n::: {.cell-output-display}\n![Particular solutions of dy/dx = 3y/(1+x).](10-differential-equations_files/figure-pdf/fig-particular-solution-family-1.pdf){#fig-particular-solution-family fig-pos='H'}\n:::\n:::\n\n\n### Exercises 10.3\n\n#### Bronze\n\n1. The general solution is $y=Ae^{2x}$. Find $A$ if $y(0)=5$.\n2. The general solution is $y=A(1+x)^3$. Find $A$ if $y(0)=4$.\n3. The general solution is $y^2=x^2+C$. Find $C$ if $y(0)=3$.\n4. The general solution is $\\ln y=x+C$. Find $y$ if $y(0)=2$.\n5. The general solution is $y=Ae^{-3t}$. Find $A$ if $y(0)=80$.\n\n#### Silver\n\n1. Solve $\\dfrac{dy}{dx}=4y$, given $y(0)=3$.\n2. Solve $\\dfrac{dy}{dx}=xy$, given $y(0)=2$.\n3. Solve $\\dfrac{dy}{dx}=\\dfrac{2y}{1+x}$, given $y(0)=5$.\n4. Solve $\\dfrac{dy}{dx}=\\dfrac{4x}{y}$, given $y(0)=1$.\n5. Solve $\\dfrac{dy}{dx}=x(y+2)$, given $y(0)=0$.\n\n#### Gold\n\n1. Solve $\\dfrac{dy}{dx}=3x^2(y-1)$, given $y(0)=2$.\n2. Solve $\\dfrac{dy}{dx}=\\dfrac{2x+1}{y}$, given $y(0)=3$.\n3. Solve $\\dfrac{dy}{dx}=y\\tan x$, given $y(0)=4$.\n4. Solve $\\dfrac{dy}{dx}=x(y-3)^2$, given $y(0)=4$.\n5. Find the solution of $\\dfrac{dy}{dx}=ky$, $y(0)=100$, if $y(5)=200$.\n\n## 10.4 Growth, decay and saturation models\n\n### Key mathematical ideas\n\nThe simplest growth model is\n\n$$\n\\dfrac{dP}{dt}=kP,\n\\quad k>0.\n$$\n\nSeparating variables gives\n\n$$\n\\dfrac{1}{P}\\dfrac{dP}{dt}=k.\n$$\n\nSo\n\n$$\n\\ln P=kt+C,\n$$\n\nand therefore\n\n$$\nP=P_0e^{kt}.\n$$\n\nThe simplest decay model is\n\n$$\n\\dfrac{dP}{dt}=-kP,\n\\quad k>0,\n$$\n\nwith solution\n\n$$\nP=P_0e^{-kt}.\n$$\n\nGrowth proportional to current amount is a useful first model, but it cannot grow forever in a restricted environment. A saturation model has the form\n\n$$\n\\dfrac{dP}{dt}=kP\\left(1-\\dfrac{P}{M}\\right),\n$$\n\nwhere $M$ is the carrying capacity.\n\n### Visualisation using R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_values <- seq(0, 12, length.out = 600)\n\nmodel_df <- data.frame(\n  t = rep(t_values, 3),\n  model = rep(c(\"growth\", \"decay\", \"saturation\"), each = length(t_values))\n)\n\nmodel_df$value <- c(\n  growth_solution(t_values, initial_value = 100, rate = 0.18),\n  growth_solution(t_values, initial_value = 100, rate = -0.18),\n  logistic_solution(t_values, capacity = 1000, initial_value = 100, rate = 0.45)\n)\n\nggplot(model_df, aes(x = t, y = value, linetype = model)) +\n  geom_line(linewidth = 1.1) +\n  labs(\n    title = \"Three model shapes\",\n    subtitle = \"Growth, decay and saturation have distinct long-term behaviour.\",\n    x = \"time\",\n    y = \"quantity\",\n    linetype = \"Model\"\n  ) +\n  book_theme()\n```\n\n::: {.cell-output-display}\n![Exponential growth, exponential decay and logistic saturation.](10-differential-equations_files/figure-pdf/fig-growth-decay-saturation-1.pdf){#fig-growth-decay-saturation fig-pos='H'}\n:::\n:::\n\n\n### Worked example\n\nA quantity $P$ grows at a rate proportional to $P$. Initially,\n\n$$\nP(0)=500.\n$$\n\nAfter $10$ years,\n\n$$\nP(10)=700.\n$$\n\nFind a model for $P$.\n\nSince\n\n$$\n\\dfrac{dP}{dt}=kP,\n$$\n\nwe have\n\n$$\nP=500e^{kt}.\n$$\n\nUsing $P(10)=700$ gives\n\n$$\n700=500e^{10k}.\n$$\n\nThus\n\n$$\ne^{10k}=\\dfrac{7}{5}.\n$$\n\nSo\n\n$$\n10k=\\ln\\left(\\dfrac{7}{5}\\right),\n$$\n\nand\n\n$$\nk=\\dfrac{1}{10}\\ln\\left(\\dfrac{7}{5}\\right).\n$$\n\nTherefore,\n\n$$\nP=500e^{\\dfrac{t}{10}\\ln(\\dfrac{7}{5})}.\n$$\n\nEquivalently,\n\n$$\nP=500\\left(\\dfrac{7}{5}\\right)^{t/10}.\n$$\n\n### Short investigation: NZ and Vietnam context\n\nThe following small dataset is a classroom-style structure for comparing a deterministic model with updated observations. Replace the values with current official values before using the activity live.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontext_df <- data.frame(\n  year = 0:5,\n  index_value = c(100, 106, 113, 121, 128, 137)\n)\n\nrate_estimate <- log(context_df$index_value[6] / context_df$index_value[1]) / 5\n\ncurve_df <- data.frame(\n  year = seq(0, 5, length.out = 400)\n)\n\ncurve_df$model <- context_df$index_value[1] * exp(rate_estimate * curve_df$year)\n\nggplot() +\n  geom_point(data = context_df, aes(x = year, y = index_value), size = 3) +\n  geom_line(data = curve_df, aes(x = year, y = model), linewidth = 1.1) +\n  labs(\n    title = \"Fitting a simple exponential model\",\n    subtitle = \"This structure can be reused with updated NZ, Vietnam or school data.\",\n    x = \"years from start\",\n    y = \"index\"\n  ) +\n  book_theme()\n```\n\n::: {.cell-output-display}\n![A deterministic curve compared with a small classroom dataset.](10-differential-equations_files/figure-pdf/fig-context-growth-data-1.pdf){#fig-context-growth-data fig-pos='H'}\n:::\n:::\n\n\n### Exercises 10.4\n\n#### Bronze\n\n1. Solve $\\dfrac{dP}{dt}=0.2P$, given $P(0)=50$.\n2. Solve $\\dfrac{dP}{dt}=-0.3P$, given $P(0)=80$.\n3. A quantity satisfies $P=100e^{0.05t}$. Find $\\dfrac{dP}{dt}$ in terms of $P$.\n4. A quantity satisfies $P=200e^{-0.1t}$. Find its half-life.\n5. For $\\dfrac{dP}{dt}=kP$, explain the meaning of $k>0$ and $k<0$.\n\n#### Silver\n\n1. A population grows from $500$ to $700$ in $10$ years according to $\\dfrac{dP}{dt}=kP$. Find $k$.\n2. A value decays from $1200$ to $900$ in $4$ years according to $\\dfrac{dV}{dt}=-kV$. Find $k$.\n3. A bacteria culture satisfies $\\dfrac{dN}{dt}=0.4N$, $N(0)=200$. Find $N(5)$.\n4. A pollutant level satisfies $\\dfrac{dC}{dt}=-0.25C$, $C(0)=60$. Find the time when $C=10$.\n5. A quantity doubles every $8$ years. Find the exponential growth constant.\n\n#### Gold\n\n1. A quantity satisfies $\\dfrac{dP}{dt}=kP$ and triples in $12$ years. Find $k$.\n2. A quantity satisfies $\\dfrac{dP}{dt}=-kP$ and halves in $6$ years. Find $k$.\n3. Solve $\\dfrac{dP}{dt}=0.4P\\left(1-\\dfrac{P}{1000}\\right)$, given $P(0)=100$.\n4. For the logistic model in Question 3, find the time when $P=800$.\n5. Show that the logistic model $\\dfrac{dP}{dt}=kP\\left(1-\\dfrac{P}{M}\\right)$ has equilibrium solutions $P=0$ and $P=M$.\n\n## 10.5 Cooling and weather-type relaxation models\n\n### Key mathematical ideas\n\nNewton's law of cooling has the form\n\n$$\n\\dfrac{dT}{dt}=-k(T-A),\n$$\n\nwhere:\n\n- $T$ is the object's temperature;\n- $A$ is the ambient temperature;\n- $k>0$ is the cooling constant.\n\nThis model is separable:\n\n$$\n\\dfrac{1}{T-A}\\dfrac{dT}{dt}=-k.\n$$\n\nSo\n\n$$\n\\ln|T-A|=-kt+C.\n$$\n\nTherefore,\n\n$$\nT=A+Ce^{-kt}.\n$$\n\nIf $T(0)=T_0$, then\n\n$$\nT=A+(T_0-A)e^{-kt}.\n$$\n\nThis form also models many **relaxation** processes: a quantity moves gradually towards a long-term level.\n\n### Visualisation using R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntime_values <- seq(0, 40, length.out = 600)\n\ncooling_df <- data.frame(\n  time = time_values,\n  temperature = cooling_solution(\n    time_values,\n    ambient = 26,\n    initial_value = 80,\n    cooling_constant = log(9 / 4) / 10\n  )\n)\n\nggplot(cooling_df, aes(x = time, y = temperature)) +\n  geom_line(linewidth = 1.1) +\n  geom_hline(yintercept = 26, linetype = \"dashed\") +\n  labs(\n    title = \"Newton cooling model\",\n    subtitle = \"The temperature approaches the ambient level without crossing it.\",\n    x = \"time in minutes\",\n    y = \"temperature in degrees Celsius\"\n  ) +\n  book_theme()\n```\n\n::: {.cell-output-display}\n![Cooling towards ambient temperature.](10-differential-equations_files/figure-pdf/fig-cooling-towards-ambient-1.pdf){#fig-cooling-towards-ambient fig-pos='H'}\n:::\n:::\n\n\n### Worked example\n\nA hot drink is placed in a room at temperature\n\n$$\n26^\\circ\\text{C}.\n$$\n\nInitially, the drink is at\n\n$$\n80^\\circ\\text{C}.\n$$\n\nAfter $10$ minutes, its temperature is\n\n$$\n50^\\circ\\text{C}.\n$$\n\nAssume\n\n$$\n\\dfrac{dT}{dt}=-k(T-26).\n$$\n\nFind $T$ in terms of $t$.\n\nThe general solution is\n\n$$\nT=26+Ce^{-kt}.\n$$\n\nUsing $T(0)=80$ gives\n\n$$\n80=26+C,\n$$\n\nso\n\n$$\nC=54.\n$$\n\nThus\n\n$$\nT=26+54e^{-kt}.\n$$\n\nUsing $T(10)=50$ gives\n\n$$\n50=26+54e^{-10k}.\n$$\n\nSo\n\n$$\n24=54e^{-10k},\n$$\n\nand\n\n$$\ne^{-10k}=\\dfrac{4}{9}.\n$$\n\nTaking logarithms,\n\n$$\n-10k=\\ln\\left(\\dfrac{4}{9}\\right).\n$$\n\nHence\n\n$$\nk=\\dfrac{1}{10}\\ln\\left(\\dfrac{9}{4}\\right).\n$$\n\nTherefore,\n\n$$\nT=26+54e^{-\\dfrac{t}{10}\\ln(\\dfrac{9}{4})}.\n$$\n\n### Short investigation: comparing ambient settings\n\nThe same drink cools differently in different ambient conditions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntime_values <- seq(0, 45, length.out = 600)\n\nambient_df <- expand.grid(\n  time = time_values,\n  place = c(\"cooler ambient\", \"warmer ambient\")\n)\n\nambient_df$ambient <- ifelse(ambient_df$place == \"cooler ambient\", 16, 30)\nambient_df$temperature <- cooling_solution(\n  ambient_df$time,\n  ambient = ambient_df$ambient,\n  initial_value = 80,\n  cooling_constant = 0.08\n)\n\nggplot(ambient_df, aes(x = time, y = temperature, linetype = place)) +\n  geom_line(linewidth = 1.1) +\n  labs(\n    title = \"Same cooling constant, different ambient temperatures\",\n    subtitle = \"This is a useful classroom link to weather data from NZ and Vietnam.\",\n    x = \"time in minutes\",\n    y = \"temperature in degrees Celsius\",\n    linetype = \"Context\"\n  ) +\n  book_theme()\n```\n\n::: {.cell-output-display}\n![Cooling curves under two illustrative ambient temperatures.](10-differential-equations_files/figure-pdf/fig-nz-vietnam-ambient-comparison-1.pdf){#fig-nz-vietnam-ambient-comparison fig-pos='H'}\n:::\n:::\n\n\n### Exercises 10.5\n\n#### Bronze\n\n1. Solve $\\dfrac{dT}{dt}=-0.2(T-20)$, given $T(0)=80$.\n2. Solve $\\dfrac{dT}{dt}=-k(T-25)$, given $T(0)=70$.\n3. A cooling model is $T=22+58e^{-0.1t}$. Find $T(0)$.\n4. A cooling model is $T=20+60e^{-0.05t}$. What is the long-term temperature?\n5. Explain why $T=A$ is a constant solution of $\\dfrac{dT}{dt}=-k(T-A)$.\n\n#### Silver\n\n1. A drink cools in a room at $20^\\circ\\text{C}$. Initially $T=90$. After $5$ minutes, $T=60$. Find $k$.\n2. For Question 1, find the time when $T=30$.\n3. Solve $\\dfrac{dT}{dt}=-0.1(T-18)$, given $T(0)=28$.\n4. A temperature warms towards $30^\\circ\\text{C}$ according to $\\dfrac{dT}{dt}=0.2(30-T)$, with $T(0)=10$. Find $T(t)$.\n5. A weather-index model satisfies $\\dfrac{dW}{dt}=-0.3(W-100)$, $W(0)=70$. Find $W(t)$.\n\n#### Gold\n\n1. A hot drink cools in ambient temperature $26^\\circ\\text{C}$. Initially $T=80$, and after $10$ minutes $T=50$. Find $T(t)$.\n2. For Question 1, find the time when $T=30$.\n3. A cold object warms towards $32^\\circ\\text{C}$. Initially it is $12^\\circ\\text{C}$ and after $5$ minutes it is $22^\\circ\\text{C}$. Find the model.\n4. Show that if $T=A+(T_0-A)e^{-kt}$, then it satisfies $\\dfrac{dT}{dt}=-k(T-A)$.\n5. In the model $T=A+Ce^{-kt}$ with $k>0$, explain why the curve approaches $A$ but never reaches it in finite time unless $C=0$.\n\n## 10.6 Deterministic finance models and stochastic context\n\n### Key mathematical ideas\n\nA simple deterministic finance model assumes a value $S$ changes at a rate proportional to itself:\n\n$$\n\\dfrac{dS}{dt}=rS.\n$$\n\nSeparating variables gives\n\n$$\n\\dfrac{1}{S}\\dfrac{dS}{dt}=r.\n$$\n\nThus\n\n$$\n\\ln S=rt+C,\n$$\n\nand\n\n$$\nS=S_0e^{rt}.\n$$\n\nThis is the deterministic backbone behind many compound-growth models.\n\nReal financial data are not smooth. Exchange rates, asset prices and interest-rate-sensitive values include random shocks. A stochastic model may add a random component, but stochastic differential equations are beyond this chapter.\n\nIn this chapter, we use only the deterministic separable model.\n\n### Visualisation using R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(9709)\n\ntime_values <- seq(0, 1, length.out = 252)\ninitial_rate <- 15000\nannual_drift <- 0.02\nannual_volatility <- 0.08\n\ndeterministic_df <- data.frame(\n  time = time_values,\n  rate_value = growth_solution(time_values, initial_rate, annual_drift),\n  path = \"deterministic\"\n)\n\nsimulated_paths <- do.call(\n  rbind,\n  lapply(1:6, function(path_id) {\n    random_steps <- rnorm(length(time_values) - 1, mean = 0, sd = sqrt(1 / 252))\n    log_values <- numeric(length(time_values))\n    log_values[1] <- log(initial_rate)\n    \n    for (i in 2:length(time_values)) {\n      log_values[i] <- log_values[i - 1] +\n        (annual_drift - 0.5 * annual_volatility^2) / 252 +\n        annual_volatility * random_steps[i - 1]\n    }\n    \n    data.frame(\n      time = time_values,\n      rate_value = exp(log_values),\n      path = paste0(\"simulated path \", path_id)\n    )\n  })\n)\n\nggplot() +\n  geom_line(\n    data = simulated_paths,\n    aes(x = time, y = rate_value, group = path),\n    alpha = 0.35\n  ) +\n  geom_line(\n    data = deterministic_df,\n    aes(x = time, y = rate_value),\n    linewidth = 1.2\n  ) +\n  labs(\n    title = \"Deterministic model and stochastic-looking variation\",\n    subtitle = \"Only the smooth deterministic model is solved in this chapter.\",\n    x = \"time in years\",\n    y = \"index value\"\n  ) +\n  book_theme()\n```\n\n::: {.cell-output-display}\n![A deterministic exponential curve with simulated noisy paths.](10-differential-equations_files/figure-pdf/fig-deterministic-finance-vs-noisy-paths-1.pdf){#fig-deterministic-finance-vs-noisy-paths fig-pos='H'}\n:::\n:::\n\n\n### Worked example\n\nA deterministic exchange-rate index $S$ satisfies\n\n$$\n\\dfrac{dS}{dt}=0.02S,\n$$\n\nwhere $t$ is measured in years.\n\nSuppose\n\n$$\nS(0)=15000.\n$$\n\nFind $S(t)$ and estimate $S(0.5)$.\n\nSince\n\n$$\n\\dfrac{dS}{dt}=0.02S,\n$$\n\nwe have\n\n$$\nS=15000e^{0.02t}.\n$$\n\nAt $t=0.5$,\n\n$$\nS(0.5)=15000e^{0.01}.\n$$\n\nThus\n\n$$\nS(0.5)\\approx15150.75.\n$$\n\nThis is not a forecast. It is a simple deterministic model for practising separable differential equations.\n\n### Short investigation\n\nUse the deterministic formula to compare different annual rates.\n\n\n::: {#tbl-deterministic-finance-values .cell}\n\n```{.r .cell-code}\nrates <- c(-0.03, 0, 0.02, 0.05)\n\ndata.frame(\n  annual_rate = rates,\n  value_after_half_year = round(15000 * exp(rates * 0.5), 2),\n  value_after_one_year = round(15000 * exp(rates), 2)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  annual_rate value_after_half_year value_after_one_year\n1       -0.03              14776.68             14556.68\n2        0.00              15000.00             15000.00\n3        0.02              15150.75             15303.02\n4        0.05              15379.73             15769.07\n```\n\n\n:::\n:::\n\n\n### Exercises 10.6\n\n#### Bronze\n\n1. Solve $\\dfrac{dS}{dt}=0.04S$, given $S(0)=1000$.\n2. Solve $\\dfrac{dS}{dt}=-0.02S$, given $S(0)=5000$.\n3. If $S=15000e^{0.02t}$, find $S(1)$.\n4. If $S=100e^{-0.1t}$, find the percentage rate of continuous decrease.\n5. Explain why $S=S_0e^{rt}$ is deterministic.\n\n#### Silver\n\n1. A value grows continuously at $3\\%$ per year from $2000$. Find its value after $5$ years.\n2. A value decreases continuously at $4\\%$ per year from $8000$. Find its value after $2$ years.\n3. A value changes from $15000$ to $15150.75$ in half a year under $\\dfrac{dS}{dt}=rS$. Find $r$.\n4. Find the time for $S=1000e^{0.06t}$ to reach $1500$.\n5. Find the time for $S=2000e^{-0.08t}$ to fall to $1200$.\n\n#### Gold\n\n1. A deterministic index satisfies $\\dfrac{dS}{dt}=rS$, $S(0)=S_0$. Prove that $S=S_0e^{rt}$.\n2. A value doubles in $3$ years under continuous growth. Find $r$.\n3. A value loses $20\\%$ in $4$ years under continuous decay. Find the decay constant $k$.\n4. Explain why a deterministic exponential model may be a poor forecast for daily exchange rates.\n5. A model satisfies $\\dfrac{dS}{dt}=rS$ and $S(1)=18000$, $S(3)=22000$. Find $r$ and $S(0)$.\n\n## STEP-style extension questions\n\nThese questions are designed to require proof, structure or exact reasoning.\n\n### STEP-style Question 1\n\nSolve\n\n$$\n\\dfrac{dy}{dx}=xy,\n\\quad y(0)=2.\n$$\n\nThen show directly by differentiation that your answer satisfies the differential equation.\n\n### STEP-style Question 2\n\nSolve\n\n$$\n\\dfrac{dy}{dx}=x(y-1)^2,\n\\quad y(0)=2.\n$$\n\nState the largest interval containing $0$ on which your solution is defined.\n\n### STEP-style Question 3\n\nA quantity $P$ satisfies the logistic differential equation\n\n$$\n\\dfrac{dP}{dt}=kP\\left(1-\\dfrac{P}{M}\\right),\n$$\n\nwhere $k>0$ and $M>0$.\n\nShow that the general solution may be written as\n\n$$\nP=\\dfrac{M}{1+Ae^{-kt}}.\n$$\n\n### STEP-style Question 4\n\nA hot object cools according to\n\n$$\n\\dfrac{dT}{dt}=-k(T-A).\n$$\n\nGiven $T(0)=T_0$, prove that\n\n$$\nT=A+(T_0-A)e^{-kt}.\n$$\n\nThen explain why the model predicts approach to ambient temperature rather than reaching it in finite time.\n\n### STEP-style Question 5\n\nA deterministic financial index satisfies\n\n$$\n\\dfrac{dS}{dt}=rS.\n$$\n\nSuppose $S(1)=18000$ and $S(3)=22000$.\n\nFind $r$ and $S(0)$ exactly in logarithmic form.\n\n## Reflection questions\n\n1. What does a differential equation describe?\n2. What does it mean to separate the variables?\n3. Why do we usually need an initial condition?\n4. Why can the same general solution represent infinitely many curves?\n5. Why does $\\dfrac{dP}{dt}=kP$ lead to exponential growth?\n6. Why does $\\dfrac{dT}{dt}=-k(T-A)$ approach an ambient value?\n7. Why is a logistic model more realistic than unlimited exponential growth in some contexts?\n8. Why is stochastic finance beyond the technique of this chapter?\n9. What can R show clearly about solution families that algebra alone may hide?\n10. What can exact separation of variables prove that a graph can only suggest?\n\n## Answers\n\n### Answers to Exercises 10.1\n\n#### Bronze\n\n1. $\\dfrac{dy}{dt}=ky$, where $k>0$.\n2. $\\dfrac{dy}{dt}=-ky$, where $k>0$.\n3. $\\dfrac{dP}{dt}=-0.05P$.\n4. $\\dfrac{dv}{dt}=-kv^2$, where $k>0$.\n5. $\\dfrac{dW}{dt}=k(M-W)$, where $k>0$.\n\n#### Silver\n\n1. $\\dfrac{dT}{dt}=-k(T-22)$, where $k>0$.\n2. $\\dfrac{dI}{dt}=kI(1000-I)$, where $k>0$.\n3. $\\dfrac{dS}{dt}=rS$.\n4. $\\dfrac{dD}{dt}=-kD$, where $k>0$.\n5. $N(0)=200$.\n\n#### Gold\n\n1. $\\dfrac{dT}{dt}=k(30-T)$, where $k>0$.\n2. $\\dfrac{dy}{dx}=kxy$, where $k>0$.\n3. $\\dfrac{dy}{dx}=-\\dfrac{ky}{1+x}$, where $k>0$.\n4. For example, $\\dfrac{dP}{dt}=kP\\left(1-\\dfrac{P}{5000}\\right)$.\n5. If $T=A$, then $T-A=0$, so $\\dfrac{dT}{dt}=0$. Therefore $T=A$ is an equilibrium solution.\n\n### Answers to Exercises 10.2\n\n#### Bronze\n\n1. $y=x^3+C$.\n2. $y=Ae^{x^2}$.\n3. $y=Ae^x$.\n4. $y^2=x^2+C$.\n5. $y=\\dfrac{1}{C-2x^2}$.\n\n#### Silver\n\n1. $y=2e^{\\dfrac{x^2}{2}+x}$.\n2. $y^2=3x^2+16$.\n3. $y=5(1+x)$, on the interval $x>-1$.\n4. $y=e^{x^2}-1$.\n5. $y=-1+\\sqrt{6x^2+9}$.\n\n#### Gold\n\n1. $y=\\dfrac{1}{1-\\dfrac{x^2}{2}}$.\n2. $y=3e^{\\sin x}$.\n3. $y=x+1$ on the interval $x>-1$.\n4. $y=\\dfrac{2}{3-2e^x}$.\n5. $y=4+e^{x^2+x}$.\n\n### Answers to Exercises 10.3\n\n#### Bronze\n\n1. $A=5$.\n2. $A=4$.\n3. $C=9$.\n4. $y=2e^x$.\n5. $A=80$.\n\n#### Silver\n\n1. $y=3e^{4x}$.\n2. $y=2e^{\\dfrac{x^2}{2}}$.\n3. $y=5(1+x)^2$, on the interval $x>-1$.\n4. $y=\\sqrt{4x^2+1}$ near $x=0$.\n5. $y=2e^{\\dfrac{x^2}{2}}-2$.\n\n#### Gold\n\n1. $y=1+e^{x^3}$.\n2. $y=\\sqrt{2x^2+2x+9}$ near $x=0$.\n3. $y=4\\sec x$ on an interval containing $0$.\n4. $y=3+\\dfrac{1}{1-\\dfrac{x^2}{2}}$.\n5. $k=\\dfrac{1}{5}\\ln2$, so $y=100e^{\\dfrac{x}{5}\\ln2}$.\n\n### Answers to Exercises 10.4\n\n#### Bronze\n\n1. $P=50e^{0.2t}$.\n2. $P=80e^{-0.3t}$.\n3. $\\dfrac{dP}{dt}=0.05P$.\n4. The half-life is $\\dfrac{\\ln2}{0.1}=10\\ln2$.\n5. $k>0$ means growth; $k<0$ means decay.\n\n#### Silver\n\n1. $k=\\dfrac{1}{10}\\ln\\left(\\dfrac{7}{5}\\right)$.\n2. $k=\\dfrac{1}{4}\\ln\\left(\\dfrac{4}{3}\\right)$.\n3. $N(5)=200e^2$.\n4. $t=4\\ln6$.\n5. $k=\\dfrac{\\ln2}{8}$.\n\n#### Gold\n\n1. $k=\\dfrac{\\ln3}{12}$.\n2. $k=\\dfrac{\\ln2}{6}$.\n3. $P=\\dfrac{1000}{1+9e^{-0.4t}}$.\n4. $t=\\dfrac{\\ln36}{0.4}=2.5\\ln36\\approx8.96$.\n5. If $P=0$ or $P=M$, then $\\dfrac{dP}{dt}=0$, so both are equilibrium solutions.\n\n### Answers to Exercises 10.5\n\n#### Bronze\n\n1. $T=20+60e^{-0.2t}$.\n2. $T=25+45e^{-kt}$.\n3. $T(0)=80$.\n4. The long-term temperature is $20^\\circ\\text{C}$.\n5. If $T=A$, then $T-A=0$, so the derivative is $0$.\n\n#### Silver\n\n1. $k=\\dfrac{1}{5}\\ln\\left(\\dfrac{7}{4}\\right)$.\n2. $t=\\dfrac{\\ln7}{k}=\\dfrac{5\\ln7}{\\ln(7/4)}$.\n3. $T=18+10e^{-0.1t}$.\n4. $T=30-20e^{-0.2t}$.\n5. $W=100-30e^{-0.3t}$.\n\n#### Gold\n\n1. $T=26+54e^{-\\dfrac{t}{10}\\ln(\\dfrac{9}{4})}$.\n2. $t=\\dfrac{10\\ln(27/2)}{\\ln(9/4)}\\approx32.1$ minutes.\n3. $T=32-20e^{-kt}$, where $k=\\dfrac{1}{5}\\ln2$.\n4. Differentiating gives $\\dfrac{dT}{dt}=-k(T_0-A)e^{-kt}=-k(T-A)$.\n5. If $C\\neq0$, then $e^{-kt}$ is positive for every finite $t$, so $T-A=Ce^{-kt}$ is never $0$.\n\n### Answers to Exercises 10.6\n\n#### Bronze\n\n1. $S=1000e^{0.04t}$.\n2. $S=5000e^{-0.02t}$.\n3. $S(1)=15000e^{0.02}\\approx15303.02$.\n4. It decreases continuously at $10\\%$ per unit time.\n5. It has no random term, so each value of $t$ gives exactly one predicted value.\n\n#### Silver\n\n1. The value is $2000e^{0.15}\\approx2323.67$.\n2. The value is $8000e^{-0.08}\\approx7384.93$.\n3. $r=0.02$.\n4. $t=\\dfrac{\\ln(3/2)}{0.06}\\approx6.76$.\n5. $t=\\dfrac{\\ln(5/3)}{0.08}\\approx6.39$.\n\n#### Gold\n\n1. Separating variables gives $\\ln S=rt+C$, so $S=Ae^{rt}$. Since $S(0)=S_0$, $A=S_0$.\n2. $r=\\dfrac{\\ln2}{3}$.\n3. $k=\\dfrac{1}{4}\\ln\\left(\\dfrac{5}{4}\\right)$.\n4. Daily exchange rates have shocks, interventions, liquidity effects and news effects, so a smooth deterministic exponential curve is only a simplified backbone.\n5. $r=\\dfrac{1}{2}\\ln\\left(\\dfrac{11}{9}\\right)$ and $S(0)=18000e^{-r}$.\n\n### Answers to STEP-style extension questions\n\n1. Separating variables gives\n   $$\n   \\int \\dfrac{1}{y}\\,dy=\\int x\\,dx.\n   $$\n   Hence\n   $$\n   \\ln|y|=\\dfrac{x^2}{2}+C.\n   $$\n   Since $y(0)=2$,\n   $$\n   y=2e^{x^2/2}.\n   $$\n   Differentiating gives\n   $$\n   \\dfrac{dy}{dx}=2e^{x^2/2}\\cdot x=xy.\n   $$\n\n2. Separate variables:\n   $$\n   \\int \\dfrac{1}{(y-1)^2}\\,dy=\\int x\\,dx.\n   $$\n   Thus\n   $$\n   -\\dfrac{1}{y-1}=\\dfrac{x^2}{2}+C.\n   $$\n   Since $y(0)=2$, we get $C=-1$. Hence\n   $$\n   \\dfrac{1}{y-1}=1-\\dfrac{x^2}{2}.\n   $$\n   Therefore,\n   $$\n   y=1+\\dfrac{1}{1-\\dfrac{x^2}{2}}.\n   $$\n   The largest interval containing $0$ is\n   $$\n   -\\sqrt2<x<\\sqrt2.\n   $$\n\n3. Separate variables:\n   $$\n   \\dfrac{dP}{P(1-P/M)}=k\\,dt.\n   $$\n   Since\n   $$\n   \\dfrac{1}{P(1-P/M)}=\\dfrac{M}{P(M-P)}\n   =\n   \\dfrac{1}{P}+\\dfrac{1}{M-P},\n   $$\n   integration gives\n   $$\n   \\ln|P|-\\ln|M-P|=kt+C.\n   $$\n   Hence\n   $$\n   \\ln\\left|\\dfrac{P}{M-P}\\right|=kt+C.\n   $$\n   Therefore\n   $$\n   \\dfrac{P}{M-P}=Be^{kt}.\n   $$\n   Rearranging gives\n   $$\n   P=\\dfrac{M}{1+Ae^{-kt}}.\n   $$\n\n4. Separating variables gives\n   $$\n   \\int \\dfrac{1}{T-A}\\,dT=\\int -k\\,dt.\n   $$\n   Hence\n   $$\n   \\ln|T-A|=-kt+C.\n   $$\n   Therefore\n   $$\n   T=A+Ce^{-kt}.\n   $$\n   Using $T(0)=T_0$ gives $C=T_0-A$, so\n   $$\n   T=A+(T_0-A)e^{-kt}.\n   $$\n   Since $e^{-kt}>0$ for finite $t$, the model approaches $A$ but does not reach it in finite time unless $T_0=A$.\n\n5. Since\n   $$\n   S=S_0e^{rt},\n   $$\n   the two conditions give\n   $$\n   18000=S_0e^r\n   $$\n   and\n   $$\n   22000=S_0e^{3r}.\n   $$\n   Dividing gives\n   $$\n   \\dfrac{11}{9}=e^{2r}.\n   $$\n   Hence\n   $$\n   r=\\dfrac{1}{2}\\ln\\left(\\dfrac{11}{9}\\right).\n   $$\n   Also\n   $$\n   S_0=18000e^{-r}\n   =\n   18000\\sqrt{\\dfrac{9}{11}}.\n   $$",
    "supporting": [
      "10-differential-equations_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}